default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: writerboy
  password: doubleclick
  database: questionnaire_development
  host: localhost
  port: 5432

test:
  <<: *default
  username: writerboy_test
  password: doubleclick_test
  database: questionnaire_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: questionnaire_production
  username: <%= ENV['PROD_USERNAME'] %>
  password: <%= ENV['PROD_PASSWORD'] %>